FROM cypress/base:12

WORKDIR /e2e

# dependencies will be installed only if the package files change
COPY ./package*.json /e2e

RUN npm i && npm cache clean --force

# Copies everything over to Docker environment
COPY . /e2e

# verify that Cypress has been installed correctly.
# running this command separately from "cypress run" will also cache its result
# to avoid verifying again when running the tests
RUN npx cypress verify
