FROM cypress/base:12

WORKDIR /e2e

# dependencies will be installed only if the package files change
COPY package*.json ./

RUN npm ci --silent

# Copies everything over to Docker environment
COPY . .

# verify that Cypress has been installed correctly.
# running this command separately from "cypress run" will also cache its result
# to avoid verifying again when running the tests
RUN npx cypress verify
