default_language_version:
  python: python3.10
exclude: "[a-zA-Z]*/(migrations)/(.)*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=server/setup.cfg]
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        args: [--config=server/pyproject.toml]
        # args: [--config=server/pyproject.toml, --check, --diff,]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.3
    hooks:
      - id: isort
        name: Reorder python imports
