# Pull Python official base image
FROM python:3.10.6-slim

# Set the working directory
ENV APP_HOME=/home/app
WORKDIR $APP_HOME

# Install git
RUN apt update \
    && apt install -y --no-install-recommends git \
    && apt autoclean

# Upgrade Pip
RUN pip install --no-cache-dir --upgrade pip

# Install pre-commit
RUN pip install pre-commit

COPY .pre-commit-config.yaml ./
COPY ./server ./server
