version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  client:
    build: ./client
    image: taxi-app-frontend:1.0.0
    volumes:
      - ./client:/home/app
      - /home/app/node_modules
    ports:
      - "3100:3000"
    depends_on:
      - db
      - server
    stdin_open: true
  server:
    build: ./server
    image: taxi-app-backend:1.0.0
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./server:/home/app/web
    ports:
      - "8100:8000"
    env_file:
      - ./server/.env.dev
    depends_on:
      - db
    links:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:latest

volumes:
  postgres-data:
