version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi_db
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
  client:
    build: ./client
    image: taxi-app-frontend:1.0.0
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - server
    stdin_open: true
  server:
    build: ./server
    image: taxi-app-backend:1.0.0
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./server:/home/app/web
    ports:
      - "8002:8000"
    env_file:
      - ./server/.env.dev
    depends_on:
      - postgres
    links:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:latest

volumes:
  postgres-data:
