version: "3.8"

services:
  pre-commit:
    build:
      context: .
      dockerfile: Dockerfile.pre-commit
    image: taxi-app-backend-pre-commit
    command: pre-commit run --all-files
    # command: bash -c "pre-commit autoupdate && pre-commit run --all-files"
    volumes:
      - .:/home/app
