version: '3.7'

services:
  pre-commit:
    build:
      context: .
      dockerfile: Dockerfile.pre-commit
    image: taxi-app-backend-pre-commit:1.0.0
    command: pre-commit run --all-files
    volumes:
      - .:/usr/src/app
