export const AUTH_USER_SET = 'AUTH_USER_SET';
export const SET_CURRENT_TRIP = 'SET_CURRENT_TRIP';
export const CLEAR_CURRENT_TRIP = 'CLEAR_CURRENT_TRIP';
export const SET_AVAILABLE_TRIPS = 'SET_AVAILABLE_TRIPS';
export const UPDATE_AVAILABLE_TRIPS = 'UPDATE_AVAILABLE_TRIPS';
export const SET_RECENT_TRIPS = 'SET_RECENT_TRIPS';
export const UPDATE_RECENT_TRIPS = 'UPDATE_RECENT_TRIPS';
export const CLEAR_TRIPS = 'CLEAR_TRIPS';
